### ISSUE TITLE
Default Values on Row Creation

### ISSUE THREAD

**Issue by lollar** [superposition-dev/lol-rm-migrations#10]
The current `default` method on the add row class only allows for varchars. It's not really a practical method.  We need to change the way that defaults work to be dynamic based on type. 

This link should provide a good reference for what we need to be covered: https://www.postgresql.org/docs/9.3/static/ddl-default.html

**Comment by reecebisel** [comment]
lollar and I talked about this over slack. We decided to use method overloading to handle any quirks in default values. Like strings needing to be wrapped in single quotes.

**Comment by reecebisel** [comment]
We can close this because pull request 14 takes care of it.
