### ISSUE TITLE
Drop Table

### ISSUE THREAD

**Issue by lollar** [superposition-dev/lol-rm-migrations#12]
We need a class that can drop a table from a schema.

**Comment by reecebisel** [comment]
Do we have a schema table too look at what tables exist, or are we planning on having postgres shout at them if the table doesn't exist?

**Comment by lollar** [comment]
we can just guard it with a postgres query and if the table doesn't exist it would just be a noop.

**Comment by reecebisel** [comment]
check out pull request 16

**Comment by lollar** [comment]
Looks good. #16 merged.
