### ISSUE TITLE
sql_string order

### ISSUE THREAD

**Issue by reecebisel** [superposition-dev/lol-rm-migrations#13]
Does it make a difference as to where the unique, default, or not null arguments end up in the final executed SQL string?

**Comment by lollar** [comment]
The only part that matters is the `of_type` depending on what we decide to do with that. The rest will work fine in any order (at least of what we have defined currently)

**Comment by reecebisel** [comment]
I think for now this is alright. It might become an issue again in the future, and we can better deal with it then.
