### ISSUE TITLE
Database Configuration script

### ISSUE THREAD

**Issue by lollar** [superposition-dev/lol-rm-migrations#2]
We need to have the ability to create a database with the CLI (pending).  There are decisions that need to be made on how we want to do this.  Currently, we will only be supporting Postgres so we just need to figure out how to script this. I'm leaning towards doing something in a `.yml` file like so:

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
```

**Comment by lollar** [comment]
I'm going to start this but any tips/suggestions would be greatly appreciated :)

**Comment by reecebisel** [comment]
I think the yaml file is familiar enough for anyone who might use this that its the right way to go

**Comment by lollar** [comment]
complete
