### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by lollar** [superposition-dev/lol-rm-migrations#5]
We need to add documentation, we can probably just do this in the README for now.

**Comment by reecebisel** [comment]
I can start of some of the documentation, however we need to start working on the CLI as well. I think keeping the CLI up to date with the code would help the documentation, but its not that big of a deal.

**Comment by lollar** [comment]
yeah, this is kinda last step since we haven't really figured out all of the different usages anyway.

**Comment by reecebisel** [comment]
The real question here is do we write documentation while we write code and change things as needed, or do we look at just writing all the documentation at once, so we only do it once. I'm good to write documentation kinda whenever.

**Comment by reecebisel** [comment]
checkout pull request 17

**Comment by lollar** [comment]
Looks good, this ticket should probably be just perpetually open but for now, I'm going to close it and I think it would be good to have documentation (README) as a requirement for all features. We can create another ticket for the doc book thing you were talking about 😸
